name: Release Draft
on:
  push:
    branches: [main]

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: ./
        id: version

      - name: Create Release Draft
        if: steps.version.outputs.has-changes == 'true'
        uses: softprops/action-gh-release@v2.6.2
        with:
          draft: true
          tag_name: ${{ steps.version.outputs.next-version-tag }}
          name: Release ${{ steps.version.outputs.next-version }}
          body: ${{ steps.version.outputs.changelog }}
          token: ${{ github.token }}
